version: '3.8'
services:
  zonocaller:
    image: zonocaller
    container_name: zonocaller
    volumes:
      - /var/log/zonocaller:/app/data
    ports:
      - "8000:8000"
    environment:
      - RUN_ONCE=${RUN_ONCE}
      - TIMEZONE=${TIMEZONE}
      - OUTPUT_FILE=${OUTPUT_FILE}
      - ZONOMI_HOSTS=${ZONOMI_HOSTS}
      - ZONOMI_API_KEY=${ZONOMI_API_KEY}
      - ZONOMI_API_ENCRYPTED=${ZONOMI_API_ENCRYPTED}
      - ZONOMI_ENCRYPTION_KEY=${ZONOMI_ENCRYPTION_KEY}
    restart: unless-stopped
